modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
modId="fusion_smithing"
version="${mod_version}"
displayName="Fusion Smithing"
logoFile="assets/fusion_smithing/icon.png"
authors="Karashok-Leo"
credits="Ported to Forge by Xiaoyu_2009"
description='''
Fusion Smithing allows you to combine the NBT data of two items in a smithing table.
'''

[[dependencies.fusion_smithing]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.fusion_smithing]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"